---
- name: Check if Apache Exists
  stat: path=/etc/init.d/apache2
  register: service_status

- name: stop apache
  service:
    name: apache2
    state: stopped
  when: service_status.stat.exists
  become: true
  notify: start nginx

- name: install nginx
  yum: 
    name: nginx 
    state: latest
  become: true
  notify: start nginx

#Add .conf file
- name: copy php.conf
  copy:
    src: ../files/php.conf
    dest: /etc/nginx/conf.d/
  become: true
  notify: reload nginx

- name: remove nginx default welcome page
  file:  
    path: /usr/share/nginx/html/index.html
    state: absent
  become: true  
  notify: reload nginx

- name: remove old files
  file:  
    path: /usr/share/nginx/html
    state: absent
  become: true  
  tags:
    - tooling-html

- name: copy html content to one level up
  copy:
    #src: /var/www/html/html
    src: "{{ WORKSPACE }}/html/"
    dest: /usr/share/nginx/html
  become: true
  tags:
    - tooling-html
  # command: cp -r /var/www/html/html/ /var/www/



