---
- name: stop apache
  service:
    name: apache2
    state: stopped
  become: true
  notify: reload nginx

- name: install nginx
  apt: 
    name: nginx 
    state: latest
  become: true
  notify: start nginx

- name: copy nginx.conf
  copy:
    src: ../files/nginx.conf
    dest: /etc/nginx/nginx.conf
  become: true
  notify: reload nginx

- name: remove nginx default welcome page
  file:  
    path: /etc/nginx/sites-enabled/default 
    state: absent
  become: true  
  notify: reload nginx



