---
- name: Check if Apache Exists
  stat: path=/etc/init.d/apache2
  register: service_status

- name: stop apache
  service:
    name: apache2
    state: stopped
  when: service_status.stat.exists
  become: true
  notify: start nginx

- name: install nginx
  apt: 
    name: nginx 
    state: latest
  become: true
  notify: start nginx

#update .conf file
# - name: copy nginx.conf
#   copy:
#     src: ../files/nginx.conf
#     dest: /etc/nginx/nginx.conf
#   become: true
#   notify: reload nginx

- name: remove nginx default welcome page
  file:  
    path: /etc/nginx/sites-enabled/default 
    state: absent
  become: true  
  notify: reload nginx

- name: copy html content to one level up
  copy:
    src: /var/www/html/html
    dest: /var/www/html
  become: true
  tags:
    - tooling-html
  # command: cp -r /var/www/html/html/ /var/www/



