---
- name: Check if Apache Exists
  stat: path=/etc/init.d/apache2
  register: service_status

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  become: true

- name: stop apache
  service:
    name: apache2
    state: stopped
  when: service_status.stat.exists
  become: true
  notify: start nginx

- name: install nginx
  yum: 
    name: nginx 
    state: latest
  become: true
  notify: start nginx

- name: remove nginx default welcome page
  file:  
    path: "{{ item }}"
    state: absent
  become: true  
  loop:
    - /var/www/html/index.nginx-debian.html
    - /etc/nginx/sites-enabled/default
    - /usr/share/nginx/html/index.html
  notify: reload nginx

- name: remove old files
  file:  
    path: /usr/share/nginx/html
    state: absent
  become: true  
  tags:
    - tooling-html

#Add .conf file
- name: copy php.conf.j2 template file
  template:
    src: ../templates/php.conf.j2
    dest: /etc/nginx/conf.d/tooling.dev.jendyjasper.com.conf
  become: true
  notify: reload nginx
  tags:
    - tooling-html

# - name: link nginx config file to sites enabled
#   file:
#     src: /etc/nginx/sites-available/tooling.dev.jendyjasper.com
#     dest: /etc/nginx/sites-enabled/default
#     state: link
#   tags:
#     - tooling-html

# - name: copy github cloned files to remote host
#   copy:
#     #src: /var/www/html/html
#     src: "{{ WORKSPACE }}/html/"
#     dest: /usr/share/nginx/html
#     # owner: www-data
#     # group: www-data
#     # mode: u=rwx,g=rw,o=rx
#   become: true
#   tags:
#     - tooling-html
#   # command: cp -r /var/www/html/html/ /var/www/

#use jenkins environment variable
- name: copy github cloned files to remote host
  copy:
    #src: /var/www/html/html
    src: "{{ lookup('ansible.builtin.env', 'WORKSPACE')}}/html/"
    dest: /usr/share/nginx/html
    # owner: www-data
    # group: www-data
    # mode: u=rwx,g=rw,o=rx
  become: true
  tags:
    - tooling-html
  # command: cp -r /var/www/html/html/ /var/www/

- name: Allow connection to database via http
  shell: setsebool -P httpd_can_network_connect_db 1
  become: true
  tags:
    - tooling-html