---
# tasks file for nginx

# - name: Update apt repo
#   apt: 
#     update_cache: yes

- name: stop apache
  service:
    name: apache2
    state: stopped
  become: true

- name: install nginx
  apt: 
    name: nginx 
    state: latest
  become: true

- name: start nginx
  service:
      name: nginx
      state: started
  become: true

- name: copy nginx.conf
  copy:
    src: ../files/nginx.conf
    dest: /etc/nginx/nginx.conf
  become: true

- name: remove nginx default welcome page
  file:  
    path: /etc/nginx/sites-enabled/default 
    state: absent
  become: true  

- name: reload nginx
  service:
      name: nginx
      state: reloaded
  become: true

