---
- name: Check if Apache Exists
  stat: path=/etc/init.d/apache2
  register: service_status
  tags:
    - nginx-setup

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  tags:
    - nginx-setup
  become: true

- name: stop apache
  service:
    name: apache2
    state: stopped
  when: service_status.stat.exists
  become: true
  # notify: start nginx
  tags:
    - nginx-setup

- name: install nginx
  yum: 
    name: nginx 
    state: latest
  become: true
  # notify: start nginx
  tags:
    - nginx-setup

- name: remove nginx default welcome page
  file:  
    path: 
      - /var/www/html/index.nginx-debian.html
      - /etc/nginx/sites-enabled/default
      - /usr/share/nginx/html/index.html
    state: absent
  become: true  
  # notify: reload nginx
  tags:
    - nginx-setup

#Add .conf file
- name: copy jendyjasper.com.j2 template file
  template:
    src: ../templates/lb-ubuntu-jendyjasper.com.j2
    dest: /etc/nginx/conf.d/jendyjasper.com.conf
  become: true
  # notify: reload nginx
  tags:
    - nginx-setup

# - name: link nginx config file to sites enabled
#   file:
#     src: /etc/nginx/sites-available/jendyjasper.com.conf
#     dest: /etc/nginx/nginx.conf
#     state: link
#     force: true
#   # notify: reload nginx
#   become: true
#   tags:
#     - nginx-setup

# - name: copy host file
#   copy:
#     src: ../files/hosts
#     dest: /etc/hosts
#   become: true
#   # notify: reload nginx
#   tags:
#     - nginx-setup

- name: reload nginx
  service:
      name: nginx
      state: reloaded
  become: true

- name: Allow connection via proxy
  shell: setsebool -P httpd_can_network_relay 1
  become: true