---
- name: Check if Apache Exists
  stat: path=/etc/init.d/apache2
  register: service_status

- name: Update Apt
  apt:
    update_cache: yes
  become: true

- name: stop apache
  service:
    name: apache2
    state: stopped
  when: service_status.stat.exists
  become: true
  notify: start nginx

- name: install nginx
  apt: 
    name: nginx 
    state: latest
  become: true
  notify: start nginx

- name: remove nginx default welcome page
  file:  
    path: 
      - /var/www/html/index.nginx-debian.html
      - /etc/nginx/sites-enabled/default
    state: absent
  become: true  
  notify: reload nginx

#Add .conf file
- name: copy jendyjasper.com.j2 template file
  template:
    src: ../templates/lb-ubuntu-jendyjasper.com.j2
    dest: /etc/nginx/sites-available/jendyjasper.com
  become: true
  notify: reload nginx

- name: link nginx config file to sites enabled
  file:
    src: /etc/nginx/sites-available/jendyjasper.com
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: reload nginx

- name: copy host file
  copy:
    src: ../files/hosts
    dest: /etc/hosts
  become: true
  notify: reload nginx
