---
- name: Check if Apache Exists
  stat: path=/etc/init.d/apache2
  register: service_status
  tags:
    - nginx-setup

- name: Update Apt
  apt:
    update_cache: yes
  become: true
  tags:
    - nginx-setup

- name: stop apache
  service:
    name: apache2
    state: stopped
  when: service_status.stat.exists
  become: true
  notify: start nginx
  tags:
    - nginx-setup

- name: install nginx
  apt: 
    name: nginx 
    state: latest
  become: true
  notify: start nginx
  tags:
    - nginx-setup

- name: remove nginx default welcome page
  file:  
    path: 
      - /var/www/html/index.nginx-debian.html
      - /etc/nginx/sites-enabled/default
    state: absent
  become: true  
  notify: reload nginx
  tags:
    - nginx-setup

#Add .conf file
- name: copy jendyjasper.com.j2 template file
  template:
    src: ../templates/lb-infradev.jendyjasper.com.j2
    dest: /etc/nginx/sites-available/infradev.jendyjasper.com
  become: true
  # notify: reload nginx
  tags:
    - nginx-setup

- name: link nginx config file to sites enabled
  file:
    src: /etc/nginx/sites-available/infradev.jendyjasper.com
    dest: /etc/nginx/sites-enabled/default
    state: link
  # notify: reload nginx
  become: true
  tags:
    - nginx-setup

- name: copy host file
  copy:
    src: ../files/infradev-hosts
    dest: /etc/hosts
  become: true
  # notify: reload nginx
  tags:
    - nginx-setup

- name: reload nginx
  service:
      name: nginx
      state: reloaded
  become: true
