---
- hosts: tooling
  name: Include dynamic variables 
  tasks:
  #import_playbook: ../static-assignments/common.yml 
    - include_tasks: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: tooling
  roles:
    - role: nginx
      become: yes
  gather_facts: true

- hosts: tooling
  roles:
    - role: php
      become: yes
  tags:
      - tooling-html
  gather_facts: true


