---
- hosts: db
  roles:
    - role: mysql
      become: yes
  gather_facts: true

- hosts: db
  name: run database script
  become: yes
  gather_facts: true
  tasks:
    - name: run script
      shell:  mysql -h 172.31.91.233 -u webaccess -p password < ../roles/mysql/files/tooling-db.sql