- hosts: nginx
  name: configure Nginx load balancer
  tasks:
    - name: Set up Nginx load balancer on ubuntu
      import_tasks: ../roles/nginx/tasks/set-up-lb.yml
      handlers:
        - name: reload nginx
          service:
            name: nginx
            state: reloaded
          become: true