---

- name: enable apache2 modules
  command: a2enmod {{ item }} 
  become: true
  loop:
    - proxy
    - proxy_balancer
    - proxy_http
    - headers
    - lbmethod_bytraffic
    - rewrite

- name: install apache2 and libxml2-dev 
  apt: 
    name: "{{ item }}"
    state: latest
  become: true
  loop:
    - apache2
    - libxml2-dev




- name: copy ports.conf
  copy:
    src: ../files/ports.conf
    dest: /etc/apache2/ports.conf
  become: true

- name: copy 000-default.conf
  copy:
    src: ../files/000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
  become: true

- name: stop nginx
  service:
    name: nginx
    state: stopped
  become: true

- name: restart apache
  service:
      name: apache2
      state: restarted
  become: true


