---
- name: Check if Nginx Exists
  stat: path=/etc/init.d/nginx
  register: service_status

- name: stop nginx
  service:
    name: nginx
    state: stopped
  when: service_status.stat.exists
  become: true
  notify: restart apache

- name: install apache2 and libxml2-dev 
  apt: 
    name: "{{ item }}"
    state: latest
  become: true
  loop:
    - apache2
    - libxml2
  notify: restart apache

- name: Check if Apache2 modules are enabled and save the result to out.txt
  shell: apache2ctl -M | grep ""{{ item }}"_module (shared)" | cat >> out.txt | sort out.txt | uniq | tee out.txt 
  loop:
  - proxy
  - proxy_balancer
  - proxy_http
  - headers
  - lbmethod_bytraffic
  - rewrite
  become: true
  register: res

- name: Print out the data in out.txt and register the result
  shell: cat out.txt 
  register: res_d

# - name: print again
#   debug: "msg={{ res_d | map(attribute='stdout') | join('\n') }}"

- name: enable apache2 modules
  when: not res_d is search(item)
  command: a2enmod {{ item }} 
  become: true
  loop:
    - proxy_balancer
    - proxy_http
    - proxy
    - headers
    - lbmethod_bytraffic
    - rewrite
  notify: restart apache


- name: copy ports.conf
  copy:
    src: ../files/ports.conf
    dest: /etc/apache2/ports.conf
  become: true
  notify: restart apache

- name: copy 000-default.conf
  copy:
    src: ../files/000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
  become: true
  notify: restart apache



