---
- name: Check if Nginx Exists
  stat: path=/etc/init.d/nginx
  register: service_status

- name: stop nginx
  service:
    name: nginx
    state: stopped
  when: service_status.stat.exists
  become: true
  notify: restart apache

- name: install apache2 and libxml2-dev 
  apt: 
    name: "{{ item }}"
    state: latest
  become: true
  loop:
    - apache2
    - libxml2
  notify: restart apache

- name: print output
  shell: apache2ctl -M | grep ""{{ item }}"_module (shared)"
  loop:
  - proxy
  - proxy_balancer
  - proxy_http
  - headers
  - lbmethod_bytraffic
  - rewrite
  become: true
  register: res

- name: print again
- debug: "msg={{ res.results | map(attribute='stdout') | join('\n') }}"

- name: enable apache2 modules
  when: item not in apache2_enabled_modules
  command: a2enmod {{ item }} 
  become: true
  loop:
    - proxy
    - proxy_balancer
    - proxy_http
    - headers
    - lbmethod_bytraffic
    - rewrite
  notify: restart apache


- name: copy ports.conf
  copy:
    src: ../files/ports.conf
    dest: /etc/apache2/ports.conf
  become: true
  notify: restart apache

- name: copy 000-default.conf
  copy:
    src: ../files/000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
  become: true
  notify: restart apache



