---
# tasks file for apache

- name: Update apt repo
  apt: 
    update_cache: yes

- name: install apache2
  apt: 
    name: apache2 
    state: latest

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present

- name: copy 000-default.conf
  copy:
    src: ../files/000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf

- name: restart apache
  service:
      name: httpd
      state: restarted