---
  - name: stop nginx
    service:
      name: nginx
      state: stopped
    become: true
    notify: restart apache

  - name: install apache2 and libxml2-dev 
    apt: 
      name: "{{ item }}"
      state: latest
    become: true
    loop:
      - apache2
      - libxml2-dev
    notify: restart apache


  - name: enable apache2 modules
    command: a2enmod {{ item }} 
    become: true
    loop:
      - proxy
      - proxy_balancer
      - proxy_http
      - headers
      - lbmethod_bytraffic
      - rewrite
    notify: restart apache


  - name: copy ports.conf
    copy:
      src: ../files/ports.conf
      dest: /etc/apache2/ports.conf
    become: true
    notify: restart apache


  - name: copy 000-default.conf
    copy:
      src: ../files/000-default.conf
      dest: /etc/apache2/sites-available/000-default.conf
    become: true
    notify: restart apache



  - handlers:
      - import_tasks: ../handlers/main.yml