[tooling]
172.31.28.89 ansible_ssh_user='ec2-user'
172.31.81.223 ansible_ssh_user='ec2-user'
172.31.83.157 ansible_ssh_user='ec2-user'

#[db]
#172.31.87.182 ansible_ssh_user='ubuntu' 

#[nginx]
#172.31.94.215 ansible_ssh_user='ec2-user'