pipeline {
  agent any
  
  stages {

    stage('SCM Checkout'){
      steps {
          git credentialsId: 'be7c03d3-2a77-4e2e-a4f7-4fae59b354d5', 
          url: 'https://github.com/JendyJasper/tooling.git'
      }
    }

    stage('Install Nginx'){
      steps {
        ansiblePlaybook credentialsId: 'ansible-jenkins-ssh', 
        disableHostKeyChecking: true, installation: 'ansible', 
        inventory: 'inventory/dev.yml', playbook: 'playbooks/site.yml', 
        skippedTags: 'tooling-html'
      }
    }

    stage("Copy html") {
      steps {
        ansiblePlaybook credentialsId: 'ansible-jenkins-ssh', 
        disableHostKeyChecking: true, installation: 'ansible', 
        inventory: '/home/ubuntu/ansible-config-mgt/inventory/dev.yml', 
        playbook: 'playbooks/site.yml', 
        tags: 'tooling-html'
      }
    }
  }
}
