pipeline {
  agent any
  
  parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

  stages {

    stage('SCM Checkout'){
      steps {
          git branch: 'master', credentialsId: 'ansible-jenkins-ssh', 
          url: 'https://github.com/JendyJasper/tooling.git'
      }
    }

    stage('Install Nginx'){
      steps {
        ansiblePlaybook credentialsId: 'ansible-jenkins-ssh', 
        disableHostKeyChecking: true, installation: 'ansible', 
        inventory: '/home/ubuntu/ansible-config-mgt/inventory/env.[inventory].yml', 
        playbook: '/home/ubuntu/ansible-config-mgt/playbooks/site.yml', 
        skippedTags: 'tooling-html'
      }
    }

    stage("Copy html") {
      steps {
        ansiblePlaybook credentialsId: 'ansible-jenkins-ssh', 
        disableHostKeyChecking: true, installation: 'ansible', 
        inventory: '/home/ubuntu/ansible-config-mgt/inventory/env.[inventory].yml',
        playbook: '/home/ubuntu/ansible-config-mgt/playbooks/copy_to_nginx.yml', 
        tags: 'tooling-html'
      }
    }

    stage("Setup Myqsl") {
      steps {
        ansiblePlaybook credentialsId: 'ansible-jenkins-ssh', 
        disableHostKeyChecking: true, installation: 'ansible', 
        inventory: '/home/ubuntu/ansible-config-mgt/inventory/env.[inventory].yml',
        playbook: '/home/ubuntu/ansible-config-mgt/playbooks/dev_data_base.yml'
        }
    }

    stage("Setup Reverse Proxy") {
      steps {
        ansiblePlaybook credentialsId: 'ansible-jenkins-ssh', 
        disableHostKeyChecking: true, installation: 'ansible', 
        inventory: '/home/ubuntu/ansible-config-mgt/inventory/env.[inventory].yml',
        playbook: '/home/ubuntu/ansible-config-mgt/playbooks/dev-lb.yml',
        tags: 'nginx-setup'
        }
    }

    stage("Clean Workspace2") {
      steps {
        cleanWs()
      }
    }
  }
}