pipeline {
    agent any

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }

    stage('Parallel') {
            parallel {
                stage('Unit Tests') {
                    steps {
                        sh 'sleep 5s'
                        sh 'echo "Running unit tests"'
                        // Add commands to run unit tests
                    }
                }

                stage('Integration Tests') {
                    steps {
                        sh 'echo "Running integration tests"'
                        // Add commands to run integration tests
                    }
                }
                
                stage('Echo Tests') {
                    steps {
                        sh 'echo "Tests"'
                        // Add commands to run integration tests
                    }
                }
            }
        }

    stage('Package') {
      steps{
        script {
          sh 'echo "Testing Package"'
        }
      }
    }

    stage('Deploy') {
      steps {
        script {
          sh 'echo "Testing Deploy"'
        }
      }

          stage('Parallel2') {
            parallel {
                stage('Unit Tests2') {
                    steps {
                        sh 'sleep 5s'
                        sh 'echo "Running unit tests"'
                        // Add commands to run unit tests
                    }
                }

                stage('Integration Tests2') {
                    steps {
                        sh 'echo "Running integration tests"'
                        // Add commands to run integration tests
                    }
                }
            }
          }
    }

    stage('Clean Up') {
      steps {
        script {
          sh 'echo "Testing Clean Up"'
        }
      }
    }
    }
}