# ---
# - hosts: uat-webservers
# - import_playbook: ../static-assignments/uat-webservers.yml

---

# # , uat-webservers, uat-database
# - hosts: nginx, tooling
# - name: Include dynamic variables 
#   # tasks:
#   #import_playbook: ../static-assignments/common.yml 
#   include: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

- hosts: nginx, tooling
- name: Configure Nginx 
  import_playbook: ../static-assignments/dev.yml

- hosts: tooling
- name: Configure Nginx 
  import_playbook: ../static-assignments/dev-file-copy.yml 
