# ---
# - hosts: all
# - import_playbook: ../static-assignments/common.yml

# - hosts: all
# - import_playbook: ../static-assignments/common-del.yml

# - hosts: uat-webservers
# - import_playbook: ../static-assignments/uat-webservers.yml

---
- hosts: uat-database, uat-webservers, lb
- name: Include dynamic variables 
  # tasks:
  #import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

# - hosts: uat-webservers
# - name: uat-webservers assignment
#   import_playbook: ../static-assignments/uat-webservers.yml

# - hosts: uat-database
# - name: uat-database configuration
#   import_playbook: ../static-assignments/uat-database.yml

# - hosts: lb
# - name: uat-lb configuration
#   import_playbook: ../static-assignments/uat-lb.yml

- name: Loadbalancers assignment
  hosts: lb
- import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required 

